---
version: '3'
services:
  tests:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./:/testing"
    command: >
      python -m pytest -ra -vv -s --log-cli-level=info --artifacts-path=artifacts/ ${EXTRA_ARGS:-tests/}
    entrypoint: []
    working_dir: /testing
  backtesting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./Apollo11.py:/freqtrade/Apollo11.py"
      - "./Saturn5.py:/freqtrade/Saturn5.py"
    command: >
      backtesting
      --timeframe=15m,
      --timeframe-detail=5m
      --enable-protections
      --strategy-list ${STRATEGY_LIST:-Saturn5 Apollo11}
      --timerange ${TIMERANGE:-20210601-20210701}
      --config user_data/data/pairlists.json
      --config user_data/data/pairlists-${STAKE_CURRENCY:-busd}.json
      --config user_data/data/${EXCHANGE:-binance}-${STAKE_CURRENCY:-busd}-static.json
      --max-open-trades ${MAX_OPEN_TRADES:-6}
      --stake-amount ${STAKE_AMOUNT:-150}
