name: CI

on: [push, pull_request]

jobs:
  Pre-Commit:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set PY Cache Key
      run: echo "PY=$(python --version --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

    - name: Pre-Commit cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Check ALL Files On Branch
      uses: pre-commit/action@v2.0.0


  Binance:
    runs-on: ubuntu-20.04
    needs:
      - Pre-Commit
    strategy:
      fail-fast: false
      matrix:
        strategy:
          - Apollo11
          - Saturn5
        stake-currency:
          - busd
          - usdt
        timerange:
          - 20210801-20210901
          - 20210901-20211001
          - 20210801-20211001
          - 20210101-20211001

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Tests Image
        run: |
          # Random sleep in order not to hit dockerhub at the same time
          sleep $(shuf -i 5-15 -n 1)
          docker-compose build tests

      - name: Run Tests
        env:
          EXTRA_ARGS: -p no:cacheprovider --exchange=binance --stake-currency=${{ matrix.stake-currency }} --strategy=${{ matrix.strategy }} tests/backtests -k ${{ matrix.timerange }}
        run: |
          mkdir artifacts
          chmod 777 artifacts
          # Random sleep in order to contain the exchanges from being hit at the same time
          sleep $(shuf -i 5-15 -n 1)
          docker-compose run --rm tests

      - name: List Artifacts
        if: always()
        run: |
          tree artifacts/

      - name: Show Backest Output
        if: always()
        run: |
          cat artifacts/binance/${{ matrix.stake-currency }}/${{ matrix.strategy }}/backtest-output-${{ matrix.timerange }}.txt

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: binance-testrun-artifacts
          path: artifacts/


  Kucoin:
    runs-on: ubuntu-20.04
    needs:
      - Pre-Commit
    strategy:
      fail-fast: false
      matrix:
        strategy:
          - Apollo11
          - Saturn5
        stake-currency:
          - usdt
        timerange:
          - 20210801-20210901
          - 20210901-20211001
          - 20210801-20211001
          - 20210101-20211001

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Tests Image
        run: docker-compose build tests

      - name: Run Tests
        env:
          EXTRA_ARGS: -p no:cacheprovider --exchange=kucoin --stake-currency=${{ matrix.stake-currency }} --strategy=${{ matrix.strategy }} tests/backtests -k ${{ matrix.timerange }}
        run: |
          mkdir artifacts
          chmod 777 artifacts
          # Random sleep in order to contain the exchanges from being hit at the same time
          sleep $(shuf -i 5-10 -n 1)
          docker-compose run --rm tests

      - name: List Artifacts
        if: always()
        run: |
          tree artifacts/

      - name: Show Backest Output
        if: always()
        run: |
          cat artifacts/kucoin/${{ matrix.stake-currency }}/${{ matrix.strategy }}/backtest-output-${{ matrix.timerange }}.txt

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: kucoin-testrun-artifacts
          path: artifacts/


  Backest-CI-Stats:
    runs-on: ubuntu-20.04
    if: always()
    needs:
      - Kucoin
      - Binance

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install -r tests/ci-requirements.txt

      - name: Download Previous Binance CI Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/workflows/scripts/download-previous-artifacts.py \
            --repo=${{ github.event.repository.full_name }} \
            --branch=main \
            --workflow=ci.yml \
            --exchange=binance \
            --name=binance-testrun-artifacts downloaded-results

      - name: Download Previous Kucoin CI Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/workflows/scripts/download-previous-artifacts.py \
            --repo=${{ github.event.repository.full_name }} \
            --branch=main \
            --workflow=ci.yml \
            --exchange=kucoin \
            --name=kucoin-testrun-artifacts downloaded-results

      - name: Download Current Binance CI Artifacts
        uses: actions/download-artifact@v2
        with:
          name: binance-testrun-artifacts
          path: downloaded-results/current

      - name: Download Current Kucoin CI Artifacts
        uses: actions/download-artifact@v2
        with:
          name: kucoin-testrun-artifacts
          path: downloaded-results/current

      - name: Show Environ
        run: |
          env

      - name: Show Downloaded Artifacts
        run: |
          tree downloaded-results

      - name: Comment CI Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/workflows/scripts/comment-ci-results.py \
            --repo=${{ github.event.repository.full_name }} downloaded-results
